### ISSUE TITLE
Where is  M_E ?

### ISSUE THREAD

**Issue by bb2103** [DarkoVeberic/LambertW#1]
FukushimaLambertW.cc and LambertW.cc
is using M_E, while the header file is missing M_E.

**Comment by DarkoVeberic** [comment]
M_E is #defined in <math.h> which should be pulled in by the existing #include <cmath>. Which compiler under which operating system do you use?

**Comment by bb2103** [comment]
windows 7 x64.
Visual Studio 2013.

**Comment by bb2103** [comment]
Solution: 

```
#define _USE_MATH_DEFINES
#include <math.h>
#include <cmath>
```

3ks
