### ISSUE TITLE
IANAL, but.. (Citation requirement)

### ISSUE THREAD

**Issue by wjakob** [DarkoVeberic/LambertW#4]
Hi Darko,

thank you for releasing this implementation. You've chosen to dual-license it under two different licenses (GPL, BSD), which makes this great for use in other contexts. However, the citation *requirement* strikes me as really unusual: you are effectively imposing an extra legal term with either of these licenses. I am not a lawyer, but it seems to me that at this point, they are not really BSD+GPL licenses anymore, but your own custom variant with a different name.

Would you be opposed to changing this to a more gentle "please cite the paper", rather than an enforced licensing condition?

Best,
Wenzel

**Comment by DarkoVeberic** [comment]
ok, you're right.
